name: Build Clio
on:
  push:
    branches:  [master, develop, develop-next]
  pull_request:
    branches:  [master, develop, develop-next]
  workflow_dispatch:

jobs:
  lint:
    name: Lint
    runs-on: ubuntu-20.04
    steps:
      - name: Get source
        uses: actions/checkout@v3

      - name: Run clang-format
        uses: XRPLF/clio-gha/lint@main

  build_clio:
    name: Build
    runs-on: [self-hosted, Linux]
    needs: lint
    steps:
      - name: Get Clio repo
        uses: actions/checkout@v3
        with:
          path: clio_src
          ref: 'develop-next'

      - name: Get Clio CI repo
        uses: actions/checkout@v3
        with:
          path: clio_ci
          repository: 'XRPLF/clio-ci'

      - name: Get GitHub actions repo
        uses: actions/checkout@v3
        with:
          repository: XRPLF/clio-gha
          path: gha # must be the same as defined in XRPLF/clio-gha

      - name: Build
        uses: XRPLF/clio-gha/build@main

      # - name: Artifact clio_tests
      #   uses: actions/upload-artifact@v2
      #   with:
      #     name: clio_output
      #     path: clio_src/build/clio_tests
